export const EMPTY_EXCALIDRAW_DATA = {
  type: 'excalidraw',
  version: 2,
  source: 'https://excalidraw.com',
  elements: [],
  appState: {
    viewBackgroundColor: '#ffffff',
    gridSize: null,
  },
  files: {},
};

// 1. System Architecture Demo Diagram
export const ARCHITECTURE_EXCALIDRAW_DATA = {
  type: 'excalidraw',
  version: 2,
  source: 'https://excalidraw.com',
  elements: [
    // Client UI Box
    {
      id: 'client-box',
      type: 'rectangle',
      x: 100,
      y: 140,
      width: 200,
      height: 100,
      strokeColor: '#3b82f6',
      backgroundColor: '#eff6ff',
      fillStyle: 'solid',
      strokeWidth: 2,
      strokeStyle: 'solid',
      roughness: 1,
      opacity: 100,
      roundness: { type: 3 },
      seed: 102030,
      version: 1,
      versionNonce: 1,
      isDeleted: false,
      boundElements: [{ type: 'arrow', id: 'arr-client-api' }],
    },
    {
      id: 'client-text',
      type: 'text',
      x: 130,
      y: 175,
      width: 140,
      height: 30,
      strokeColor: '#1d4ed8',
      backgroundColor: 'transparent',
      fillStyle: 'solid',
      strokeWidth: 1,
      strokeStyle: 'solid',
      roughness: 0,
      opacity: 100,
      text: '🖥️ Web Client\nReact + Tailwind',
      fontSize: 14,
      fontFamily: 1,
      textAlign: 'center',
      verticalAlign: 'middle',
      containerId: 'client-box',
      originalText: '🖥️ Web Client\nReact + Tailwind',
      lineHeight: 1.2,
    },
    // Arrow from Client to API Gateway
    {
      id: 'arr-client-api',
      type: 'arrow',
      x: 300,
      y: 190,
      width: 100,
      height: 0,
      strokeColor: '#64748b',
      backgroundColor: 'transparent',
      fillStyle: 'solid',
      strokeWidth: 2,
      strokeStyle: 'solid',
      roughness: 1,
      opacity: 100,
      points: [
        [0, 0],
        [100, 0],
      ],
      startBinding: { elementId: 'client-box', focus: 0, gap: 4 },
      endBinding: { elementId: 'api-box', focus: 0, gap: 4 },
      endArrowhead: 'arrow',
    },
    // API Gateway Box
    {
      id: 'api-box',
      type: 'rectangle',
      x: 400,
      y: 140,
      width: 210,
      height: 100,
      strokeColor: '#8b5cf6',
      backgroundColor: '#f5f3ff',
      fillStyle: 'solid',
      strokeWidth: 2,
      strokeStyle: 'solid',
      roughness: 1,
      opacity: 100,
      roundness: { type: 3 },
      seed: 203040,
      version: 1,
      versionNonce: 1,
      isDeleted: false,
      boundElements: [
        { type: 'arrow', id: 'arr-client-api' },
        { type: 'arrow', id: 'arr-api-db' },
        { type: 'arrow', id: 'arr-api-cache' },
      ],
    },
    {
      id: 'api-text',
      type: 'text',
      x: 430,
      y: 175,
      width: 150,
      height: 30,
      strokeColor: '#6d28d9',
      backgroundColor: 'transparent',
      fillStyle: 'solid',
      strokeWidth: 1,
      strokeStyle: 'solid',
      roughness: 0,
      opacity: 100,
      text: '⚡ API Gateway\nExpress + REST',
      fontSize: 14,
      fontFamily: 1,
      textAlign: 'center',
      verticalAlign: 'middle',
      containerId: 'api-box',
      originalText: '⚡ API Gateway\nExpress + REST',
      lineHeight: 1.2,
    },
    // Arrow from API to Database
    {
      id: 'arr-api-db',
      type: 'arrow',
      x: 610,
      y: 170,
      width: 110,
      height: -50,
      strokeColor: '#64748b',
      backgroundColor: 'transparent',
      fillStyle: 'solid',
      strokeWidth: 2,
      strokeStyle: 'solid',
      roughness: 1,
      opacity: 100,
      points: [
        [0, 0],
        [110, -50],
      ],
      startBinding: { elementId: 'api-box', focus: 0, gap: 4 },
      endBinding: { elementId: 'db-box', focus: 0, gap: 4 },
      endArrowhead: 'arrow',
    },
    // Database Box
    {
      id: 'db-box',
      type: 'rectangle',
      x: 720,
      y: 70,
      width: 190,
      height: 90,
      strokeColor: '#10b981',
      backgroundColor: '#ecfdf5',
      fillStyle: 'solid',
      strokeWidth: 2,
      strokeStyle: 'solid',
      roughness: 1,
      opacity: 100,
      roundness: { type: 3 },
      seed: 304050,
      version: 1,
      versionNonce: 1,
      isDeleted: false,
      boundElements: [{ type: 'arrow', id: 'arr-api-db' }],
    },
    {
      id: 'db-text',
      type: 'text',
      x: 740,
      y: 100,
      width: 150,
      height: 30,
      strokeColor: '#047857',
      backgroundColor: 'transparent',
      fillStyle: 'solid',
      strokeWidth: 1,
      strokeStyle: 'solid',
      roughness: 0,
      opacity: 100,
      text: '🗄️ Primary DB\nIndexedDB / Store',
      fontSize: 14,
      fontFamily: 1,
      textAlign: 'center',
      verticalAlign: 'middle',
      containerId: 'db-box',
      originalText: '🗄️ Primary DB\nIndexedDB / Store',
      lineHeight: 1.2,
    },
    // Arrow from API to Cache
    {
      id: 'arr-api-cache',
      type: 'arrow',
      x: 610,
      y: 210,
      width: 110,
      height: 50,
      strokeColor: '#64748b',
      backgroundColor: 'transparent',
      fillStyle: 'solid',
      strokeWidth: 2,
      strokeStyle: 'solid',
      roughness: 1,
      opacity: 100,
      points: [
        [0, 0],
        [110, 50],
      ],
      startBinding: { elementId: 'api-box', focus: 0, gap: 4 },
      endBinding: { elementId: 'cache-box', focus: 0, gap: 4 },
      endArrowhead: 'arrow',
    },
    // Cache Box
    {
      id: 'cache-box',
      type: 'rectangle',
      x: 720,
      y: 220,
      width: 190,
      height: 90,
      strokeColor: '#f59e0b',
      backgroundColor: '#fffbeb',
      fillStyle: 'solid',
      strokeWidth: 2,
      strokeStyle: 'solid',
      roughness: 1,
      opacity: 100,
      roundness: { type: 3 },
      seed: 405060,
      version: 1,
      versionNonce: 1,
      isDeleted: false,
      boundElements: [{ type: 'arrow', id: 'arr-api-cache' }],
    },
    {
      id: 'cache-text',
      type: 'text',
      x: 740,
      y: 250,
      width: 150,
      height: 30,
      strokeColor: '#b45309',
      backgroundColor: 'transparent',
      fillStyle: 'solid',
      strokeWidth: 1,
      strokeStyle: 'solid',
      roughness: 0,
      opacity: 100,
      text: '⚡ Memory Cache\nHot Note Cache',
      fontSize: 14,
      fontFamily: 1,
      textAlign: 'center',
      verticalAlign: 'middle',
      containerId: 'cache-box',
      originalText: '⚡ Memory Cache\nHot Note Cache',
      lineHeight: 1.2,
    },
    // Sticky Note Note/Tip
    {
      id: 'sticky-note',
      type: 'rectangle',
      x: 100,
      y: 300,
      width: 320,
      height: 110,
      strokeColor: '#d97706',
      backgroundColor: '#fef3c7',
      fillStyle: 'solid',
      strokeWidth: 1,
      strokeStyle: 'solid',
      roughness: 1,
      opacity: 100,
      roundness: { type: 2 },
      seed: 506070,
      version: 1,
      versionNonce: 1,
      isDeleted: false,
    },
    {
      id: 'sticky-text',
      type: 'text',
      x: 115,
      y: 320,
      width: 290,
      height: 70,
      strokeColor: '#78350f',
      backgroundColor: 'transparent',
      fillStyle: 'solid',
      strokeWidth: 1,
      strokeStyle: 'solid',
      roughness: 0,
      opacity: 100,
      text: '💡 Pro Tip:\nUse Excalidraw tools to sketch wireframes,\narchitecture, or database ERDs directly\nin your notes workspace!',
      fontSize: 13,
      fontFamily: 1,
      textAlign: 'left',
      verticalAlign: 'top',
      containerId: 'sticky-note',
      originalText: '💡 Pro Tip:\nUse Excalidraw tools to sketch wireframes,\narchitecture, or database ERDs directly\nin your notes workspace!',
      lineHeight: 1.3,
    },
  ],
  appState: {
    viewBackgroundColor: '#ffffff',
    gridSize: null,
  },
  files: {},
};

export const DEFAULT_EXCALIDRAW_DATA = ARCHITECTURE_EXCALIDRAW_DATA;

// 2. Flowchart Template
export const FLOWCHART_EXCALIDRAW_DATA = {
  type: 'excalidraw',
  version: 2,
  source: 'https://excalidraw.com',
  elements: [
    {
      id: 'flow-start',
      type: 'ellipse',
      x: 160,
      y: 80,
      width: 140,
      height: 70,
      strokeColor: '#10b981',
      backgroundColor: '#d1fae5',
      fillStyle: 'solid',
      strokeWidth: 2,
      strokeStyle: 'solid',
      roughness: 1,
      opacity: 100,
      roundness: { type: 2 },
      seed: 111222,
      version: 1,
      versionNonce: 1,
      isDeleted: false,
    },
    {
      id: 'flow-start-text',
      type: 'text',
      x: 180,
      y: 105,
      width: 100,
      height: 20,
      strokeColor: '#065f46',
      text: 'Start Process',
      fontSize: 14,
      fontFamily: 1,
      textAlign: 'center',
      verticalAlign: 'middle',
      containerId: 'flow-start',
      originalText: 'Start Process',
    },
    {
      id: 'flow-arr-1',
      type: 'arrow',
      x: 230,
      y: 150,
      width: 0,
      height: 60,
      strokeColor: '#64748b',
      strokeWidth: 2,
      points: [[0, 0], [0, 60]],
      endArrowhead: 'arrow',
    },
    {
      id: 'flow-decision',
      type: 'diamond',
      x: 145,
      y: 210,
      width: 170,
      height: 100,
      strokeColor: '#f59e0b',
      backgroundColor: '#fef3c7',
      fillStyle: 'solid',
      strokeWidth: 2,
      strokeStyle: 'solid',
      roughness: 1,
      opacity: 100,
      roundness: { type: 2 },
      seed: 333444,
      version: 1,
      versionNonce: 1,
      isDeleted: false,
    },
    {
      id: 'flow-decision-text',
      type: 'text',
      x: 165,
      y: 245,
      width: 130,
      height: 30,
      strokeColor: '#92400e',
      text: 'Valid Request?',
      fontSize: 14,
      fontFamily: 1,
      textAlign: 'center',
      verticalAlign: 'middle',
      containerId: 'flow-decision',
      originalText: 'Valid Request?',
    },
    {
      id: 'flow-arr-yes',
      type: 'arrow',
      x: 315,
      y: 260,
      width: 90,
      height: 0,
      strokeColor: '#10b981',
      strokeWidth: 2,
      points: [[0, 0], [90, 0]],
      endArrowhead: 'arrow',
    },
    {
      id: 'flow-success-box',
      type: 'rectangle',
      x: 405,
      y: 220,
      width: 160,
      height: 80,
      strokeColor: '#3b82f6',
      backgroundColor: '#eff6ff',
      fillStyle: 'solid',
      strokeWidth: 2,
      roundness: { type: 3 },
      isDeleted: false,
    },
    {
      id: 'flow-success-text',
      type: 'text',
      x: 420,
      y: 245,
      width: 130,
      height: 30,
      strokeColor: '#1e40af',
      text: 'Process Action ✅',
      fontSize: 14,
      fontFamily: 1,
      textAlign: 'center',
      verticalAlign: 'middle',
      containerId: 'flow-success-box',
      originalText: 'Process Action ✅',
    },
  ],
  appState: {
    viewBackgroundColor: '#ffffff',
    gridSize: null,
  },
  files: {},
};

export const DEFAULT_THEME_BG_COLORS = new Set([
  '#ffffff',
  '#121212',
  '#1e1e1e',
  '#181818',
  '#002b36',
  '#00212b',
  '#fdf6e3',
  '#eee8d5',
  '#272822',
  '#1e1f1c',
  '#000000',
  'transparent',
]);

export function getThemeCanvasColor(themeId: string): string {
  switch (themeId) {
    case 'vs-light':
      return '#ffffff';
    case 'vs-dark':
      return '#1e1e1e';
    case 'solarized-light':
      return '#fdf6e3';
    case 'solarized-dark':
      return '#002b36';
    case 'monokai':
      return '#272822';
    case 'high-contrast-dark':
      return '#000000';
    default:
      return '#ffffff';
  }
}

export function parseExcalidrawContent(rawText: string, defaultBgColor: string = '#ffffff'): any {
  const fallbackBg = defaultBgColor || '#ffffff';
  if (!rawText || !rawText.trim()) {
    return {
      type: 'excalidraw',
      version: 2,
      source: 'https://excalidraw.com',
      elements: [],
      appState: {
        viewBackgroundColor: fallbackBg,
        gridSize: null,
      },
      files: {},
    };
  }
  try {
    const parsed = JSON.parse(rawText);
    if (typeof parsed === 'object' && parsed !== null) {
      const existingBg = parsed.appState?.viewBackgroundColor;
      // If no bg or if it's one of the standard theme/default colors, apply the active theme background
      const shouldApplyThemeBg = !existingBg || DEFAULT_THEME_BG_COLORS.has(String(existingBg).toLowerCase());
      const viewBackgroundColor = shouldApplyThemeBg ? fallbackBg : existingBg;

      return {
        type: 'excalidraw',
        version: 2,
        source: 'https://excalidraw.com',
        elements: Array.isArray(parsed.elements) ? parsed.elements : [],
        appState: {
          gridSize: parsed.appState?.gridSize || null,
          ...(parsed.appState || {}),
          viewBackgroundColor,
        },
        files: parsed.files || {},
      };
    }
  } catch {
    // If invalid JSON, return empty diagram
  }
  return {
    type: 'excalidraw',
    version: 2,
    source: 'https://excalidraw.com',
    elements: [],
    appState: {
      viewBackgroundColor: fallbackBg,
      gridSize: null,
    },
    files: {},
  };
}
